spring:
  datasource:
    url: jdbc:mysql://localhost:3300/test
    username: root
    password: mysql_source
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10
      connection-timeout: 50000
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baselineVersion: 0
